# The address on which the server should listen.
webserver_address = "[::]:3009"

# The Fabric ID to use for the Matter Controller.
matter_fabric_id = 2000

# The file in which to store Matter controller state.
matter_data_path = "matter-influx/controller-state.bin"

# The directory of PAA root certificates.
paa_dir = "/usr/share/matter-influx/paa-root-certs"

# The directory of CD certificates.
cd_dir = "/usr/share/matter-influx/cd-certs"
